# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mafia.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmafia.proto\x12\x05mafia\"\'\n\x06SingUp\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07game_id\x18\x02 \x01(\t\"2\n\x0eSingUpResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0f\n\x07players\x18\x02 \x03(\t\"1\n\x10SubscribeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07game_id\x18\x02 \x01(\t\"#\n\x05\x45xite\x12\x0c\n\x04\x64\x65\x61\x64\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\"P\n\x11SubscribeResponse\x12\x10\n\x08\x63onnecte\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x05\x65xite\x18\x03 \x01(\x0b\x32\x0c.mafia.Exite\"\x07\n\x05\x45mpty2\xa2\x02\n\x05Mafia\x12\x32\n\x08GoSingUp\x12\r.mafia.SingUp\x1a\x15.mafia.SingUpResponse\"\x00\x12Q\n\x18SubscribeToNotifications\x12\x17.mafia.SubscribeRequest\x1a\x18.mafia.SubscribeResponse\"\x00\x30\x01\x12.\n\rDisconectRoom\x12\r.mafia.SingUp\x1a\x0c.mafia.Empty\"\x00\x12\x35\n\x0b\x43onnectRoom\x12\r.mafia.SingUp\x1a\x15.mafia.SingUpResponse\"\x00\x12+\n\nDeadSignal\x12\r.mafia.SingUp\x1a\x0c.mafia.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mafia_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SINGUP._serialized_start=22
  _SINGUP._serialized_end=61
  _SINGUPRESPONSE._serialized_start=63
  _SINGUPRESPONSE._serialized_end=113
  _SUBSCRIBEREQUEST._serialized_start=115
  _SUBSCRIBEREQUEST._serialized_end=164
  _EXITE._serialized_start=166
  _EXITE._serialized_end=201
  _SUBSCRIBERESPONSE._serialized_start=203
  _SUBSCRIBERESPONSE._serialized_end=283
  _EMPTY._serialized_start=285
  _EMPTY._serialized_end=292
  _MAFIA._serialized_start=295
  _MAFIA._serialized_end=585
# @@protoc_insertion_point(module_scope)
